fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Taseera\UserBundle\Entity\User
    from_email:
          address: "%mailer_user%"
          sender_name: "%mailer_user%"
    service:
        user_manager: pugx_user_manager